#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py makemigrations

python manage.py migrate

#python manage.py runserver 0.0.0.0:8000

python manage.py collectstatic --no-input

gunicorn backend.wsgi:application --bind 0.0.0.0:9999
