# Generated by Django 4.0.6 on 2022-08-10 14:15

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset_uuid', models.CharField(blank=True, max_length=100, null=True)),
                ('upload_status', models.CharField(choices=[('empty', 'Empty'), ('ready', 'Ready'), ('failed', 'Failed'), ('processing', 'Processing'), ('completed', 'Completed')], default='processing', max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(null=True, upload_to=main.models.save_predict_files)),
                ('predict_status', models.CharField(choices=[('empty', 'Empty'), ('ready', 'Ready'), ('failed', 'Failed'), ('processing', 'Processing'), ('completed', 'Completed')], default='processing', max_length=15)),
                ('dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prediction_set', to='main.dataset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Datafile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(null=True, upload_to=main.models.save_dataset_files)),
                ('type', models.CharField(choices=[('texture', 'Texture'), ('obj', 'Obj'), ('mtl', 'Mtl')], default='texture', max_length=15)),
                ('dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_set', to='main.dataset')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
