# Generated by Django 4.0.6 on 2022-09-17 16:19

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('burn_type', models.CharField(choices=[('s', 'Scald'), ('g', 'Grease'), ('n', 'Contact'), ('f', 'Flame'), ('c', 'Chemical'), ('e', 'Electric'), ('o', 'Other')], max_length=250)),
                ('comments', models.TextField(blank=True, max_length=1000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset_uuid', models.CharField(blank=True, max_length=100, null=True)),
                ('upload_status', models.CharField(choices=[('empty', 'Empty'), ('ready', 'Ready'), ('failed', 'Failed'), ('processing', 'Processing'), ('completed', 'Completed')], default='processing', max_length=15)),
                ('data_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataset_set', to='main.datainfo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Medician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('sex', models.CharField(choices=[('f', 'Female'), ('m', 'Male'), ('u', 'Unsure')], max_length=1)),
                ('height', models.FloatField(blank=True, default=0, null=True)),
                ('weight', models.FloatField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('medician_id', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('sex', models.CharField(choices=[('f', 'Female'), ('m', 'Male'), ('u', 'Unsure')], max_length=1)),
                ('height', models.FloatField(blank=True, default=0, null=True)),
                ('weight', models.FloatField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('patient_id', models.CharField(blank=True, default='', max_length=250, null=True)),
            ],
            options={
                'verbose_name_plural': 'patients',
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(null=True, upload_to=main.models.save_predict_files)),
                ('predict_status', models.CharField(choices=[('empty', 'Empty'), ('ready', 'Ready'), ('failed', 'Failed'), ('processing', 'Processing'), ('completed', 'Completed')], default='processing', max_length=15)),
                ('dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prediction_set', to='main.dataset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='datainfo',
            name='medician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medician_case_set', to='main.medician'),
        ),
        migrations.AddField(
            model_name='datainfo',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_case_set', to='main.patient'),
        ),
        migrations.CreateModel(
            name='Datafile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(null=True, upload_to=main.models.save_dataset_files)),
                ('type', models.CharField(choices=[('texture', 'Texture'), ('obj', 'Obj'), ('mtl', 'Mtl')], default='texture', max_length=15)),
                ('dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_set', to='main.dataset')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
