# Generated by Django 4.0.6 on 2022-07-10 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_prediction_alter_dataset_dataset_uuid_delete_predict_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datafile',
            old_name='file_url',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='prediction',
            old_name='file_url',
            new_name='file',
        ),
    ]
